apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjs-config
data:
  # === Core Secrets (non-sensitive placeholders, for demo only â€” move real secrets to Kubernetes Secrets) ===
  NEXT_PUBLIC_LOGIN_KEY: '-@!8A0P.!nm099(+'
  NEXT_PUBLIC_LOGIN_IV: 'i+!_Ay(1_9-*!71O'
  NEXT_PUBLIC_NIP_USERNAME: 'vigos'
  NEXT_PUBLIC_NIP_PASSWORD: 'password12'

  # === Environment ===
  NEXT_PUBLIC_ENABLE_2FA: 'false'
  NEXT_PUBLIC_ENV: 'production'

  # === Base URLs ===
  NEXT_PUBLIC_SEARCH_BASE_URL: 'https://ibaas-search-api.k9.isw.la'
  NEXT_PUBLIC_REPORT_BASE_URL: 'https://ibaas-revamp-reports.k9.isw.la'
  NEXT_PUBLIC_END_OF_DAY_BASE_URL: 'http://ibaas-endofbusinessprocess.k9.isw.la'
  NEXT_PUBLIC_AUTH_FA_BASE_URL: 'https://ibaas-2fa-generator-service.k9.isw.la'
  NEXT_PUBLIC_BASE_URL: 'https://ibaas-api.k9.isw.la'
  NEXT_PUBLIC_ENDOFDAY_URL: 'https://ibaas-endofbusinessprocess.k9.isw.la'
  NEXT_PUBLIC_NIP_BASE_URL: 'https://nip-core-banking-interface.k9.isw.la'
  NEXT_PUBLIC_REPORTS_BASE_URL: 'https://ibaas-revamp-reports.k9.isw.la'
  NEXT_PUBLIC_IMAGE_UPLOAD_BASE_URL: 'https://ibaasfilestorage.k9.isw.la'
